---
version: "3.5"
services:
  articles_api:
    container_name: ffxblue-articles-api
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    working_dir: /app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - ./.env
    volumes:
      - ./.:/app/:rw
    depends_on:
      - db
    networks:
      - ffxblue-network
    command: [ "./scripts/wait-for-it.sh", "db:3306", "--", "./scripts/entrypoint.sh" ]

  db:
    container_name: ffxblue-api-db
    image: mysql:5.6
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME:-ffxblue}
      - MYSQL_USER=${DB_USER:-ffxblue}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    networks:
      - ffxblue-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10

networks:
  ffxblue-network:
    name: ffxblue-articles-api
    driver: "bridge"
